pipeline {
    agent any
    environment {
        CI = 'true'
        REACT_APP_OMDB_KEY = 'your key'
        IMAGE_REGISTRY = 'your registry'
        IMAGE_VERSION = "1.${env.BUILD_NUMBER}"
        IMAGE_NAME = "${IMAGE_REGISTRY}/didactic-image:${IMAGE_VERSION}"
        SERVICE_NAME = "didactic"
    }
    stages {
        stage('Clone Sources') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/khofesh/didactic-invention.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh "docker build --build-arg REACT_APP_OMDB_KEY=${REACT_APP_OMDB_KEY} -t ${IMAGE_NAME} -f ./Dockerfile ."
            }
        }
        stage("Push to Google Container Registry"){
            steps{
                sh "docker push ${IMAGE_NAME}"
            }
        }
        stage ("Prune docker images"){
            steps{
                sh "docker image prune"
            }
        }
        stage("Deploy new image to Cloud Run"){
            steps{
                sh "gcloud run deploy ${SERVICE_NAME} --image ${IMAGE_NAME} --platform=managed --region=us-central1 --port=8080 --allow-unauthenticated"
            }
        }
    }
}